export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

// Rootlayoutはhtmlを出力する関数コンポーネント
export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='body-class'>{children}</body>
    </html>
  );
}
